import React from 'react';

const STYLES = {
  label: { display: 'block', color: '#374151', fontSize: '12px', fontWeight: '600', marginBottom: '6px', fontFamily: "'Inter', sans-serif", textTransform: 'uppercase', letterSpacing: '0.3px' },
  input: { width: '100%', padding: '10px 14px', background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: '8px', color: '#111827', fontSize: '13px', fontFamily: "'Inter', sans-serif", outline: 'none', boxSizing: 'border-box', transition: 'border 0.15s' },
};

function countWords(text) {
  if (!text || !text.trim()) return 0;
  return text.trim().split(/\s+/).length;
}

export default function Summary({ data = '', onChange, resumeContext }) {
  const insertFormatting = (prefix, suffix = '') => {
    onChange(data + prefix + suffix);
  };

  const handleAiWriter = async () => {
    try {
      const res = await fetch('/api/improve-section', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ section_type: 'summary', content: data, instruction: 'Write a professional summary', resumeContext }),
      });
      const resData = await res.json();
      if (resData.status === 'success' && resData.improved) {
        onChange(resData.improved);
      } else {
        onChange(data + ' (Generated by AI)');
      }
    } catch (e) {
      onChange(data + ' (Generated)');
    }
  };

  const wordCount = countWords(data);
  const wordColor = wordCount === 0 ? '#9CA3AF' : wordCount < 20 ? '#DC2626' : wordCount < 50 ? '#EAB308' : '#16A34A';
  const wordLabel = wordCount === 0 ? 'Write 50–200 words for best results' : wordCount < 20 ? `${wordCount} words — too short` : wordCount > 200 ? `${wordCount} words — consider shortening` : `${wordCount} words ✔`;

  return (
    <div>
      <div style={{ border: '1px solid #E5E7EB', borderRadius: '8px', background: '#F9FAFB', overflow: 'hidden' }}>
        <div style={{ display: 'flex', padding: '8px', borderBottom: '1px solid #E5E7EB', gap: '8px', background: '#FFFFFF' }}>
          <button onClick={() => insertFormatting('**', '**')} style={{ background: 'none', border: 'none', fontWeight: 'bold', cursor: 'pointer', padding: '4px 8px', borderRadius: '4px' }}>B</button>
          <button onClick={() => insertFormatting('*', '*')} style={{ background: 'none', border: 'none', fontStyle: 'italic', cursor: 'pointer', padding: '4px 8px', borderRadius: '4px' }}>I</button>
          <button onClick={() => insertFormatting('__', '__')} style={{ background: 'none', border: 'none', textDecoration: 'underline', cursor: 'pointer', padding: '4px 8px', borderRadius: '4px' }}>U</button>
          <button onClick={() => insertFormatting('\n- ')} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '4px 8px', borderRadius: '4px' }}>•</button>
          <div style={{ flex: 1 }} />
          <button onClick={handleAiWriter} style={{ background: 'none', border: 'none', color: '#2563EB', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}>
            ✨ Get help with writing
          </button>
        </div>
        <textarea
          value={data || ''}
          onChange={(e) => onChange(e.target.value)}
          style={{ ...STYLES.input, border: 'none', borderRadius: '0', minHeight: '150px', resize: 'vertical' }}
          placeholder="e.g. Passionate software engineer with 5+ years of experience..."
        />
        <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 12px', background: '#FFFFFF', borderTop: '1px solid #E5E7EB', alignItems: 'center' }}>
          <button onClick={handleAiWriter} style={{ background: '#2563EB', color: 'white', border: 'none', padding: '6px 12px', borderRadius: '16px', fontSize: '13px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}>
            ✨ Ask AI writer
          </button>
          <span style={{ fontSize: '12px', color: wordColor, display: 'flex', alignItems: 'center', gap: '4px', transition: 'color 0.2s' }}>
            {wordLabel}
          </span>
        </div>
      </div>
    </div>
  );
}
